version: '2'

services:
  app:
    image: 'webapp-kafka:latest'
    build:
      context: .
    container_name: webapp-kafka
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kafkadb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8082:8082"
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db-kafka
    environment:
      - POSTGRES_DB=kafkadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
